### PR TITLE
adjust xml-encoded '&' for Location header

### PR DESCRIPTION
**Pull request by matthewbednarski**
In the method `performRedirectForShortcode()`, adjust the xml-encoded '&amp;' for the `Location` header, replacing `'amp;'` with `''`. (

### CODE REVIEW

**Comment by mgazdzik** [comment]
Hi @matthewbednarski ,

 Thanks for providing pull request. However before we release this code would you mind sharing some details about use case you want to fix with this?

From what I see you want to unescape ampersands in redirect URL, but shouldn't URL retrieved from database be already properly encoded in first place? Also replacement you provided seems like a potential failure point when actuall url really contains `amp;` , but not `&amp`.

Please let me know what you think?

**Comment by matthewbednarski** [comment]
Hi @mgazdzik,

I didn't know how seriously you would take the pull-request!  It could be considered close to what is requested in #22, except I would agree with you on the fact that I don't need the other fields, I just want to paste my url and/or get it directly from an `API` call.

It was just a quick fix, and is definitely not as robust as it should be.  The case I needed to cover is the use of shortened urls with campaign tracking query parameters (`pk_campaign` and `pk_kwd`).  It's an edge case, but given the nature of Piwik and your plugin I can imagine it could be useful to other Piwik users. 

Your plugin saves the shortened url after xml/html encoding it, so a more robust solution would be to xml/html decode just before setting the  `Location` header in the `performRedirectForShortcode()` method.

If you think that would be useful I can give that a try.

**Comment by mgazdzik** [comment]
@matthewbednarski, I hope you didn't feel offended by my question. My goal is to keep unnecessary code away from repo, hence I'm aiming to understand why given change is to be introduced and to find if it isn't only a fix for one of many cases or 'fix one & break two others' solution - which happen from time to time ;)

Apart from above - thanks for clarifying your goal. I agree that this would be a good addition for plugin itself.
Therefore - if you're feeling like giving a shot to sanitizing values during db reads, please go ahead. Also it would be awesome to have a test case covering this against future regressions.
If you're not comfortable with unit/integration tests in Piwik I'd be glad to also add this. 

Please let me know if you want to give it a try or would rather wait a bit for me to add this and make a new release.

Cheers!

**Comment by matthewbednarski** [comment]
No, I wasn't offended at all!  I'm new to the `php` world in general and definitely don't want to step on any toes.  

It's a rainy weekend in my part of Italy so I'll go ahead and give it a try, with the unit-test as well.   

Take care,

Matt

**Comment by mgazdzik** [comment]
Hi @matthewbednarski,
 I took liberty of fixing issue you were describing - changes are available in PR https://github.com/mgazdzik/plugin-ShortcodeTracker/pull/24

I'll merge those changes and release as soon as build goes green.
In meantime if you like, please feel free to check code from this branch to see if it works for you.

Cheers,
Michal

**Comment by mgazdzik** [comment]
closing this PR as this code doesn't solve actual problem, just it's symptoms. proper fix is in #24

**Pull request closed without merging**
